package Model;
// Generated 10 juil. 2018 23:06:08 by Hibernate Tools 4.3.1



/**
 * Agence generated by hbm2java
 */
public class Agence  implements java.io.Serializable {


     private int idAgence;
     private String nom;

    public Agence() {
    }

	
    public Agence(int idAgence) {
        this.idAgence = idAgence;
    }
    public Agence(int idAgence, String nom) {
       this.idAgence = idAgence;
       this.nom = nom;
    }
   
    public int getIdAgence() {
        return this.idAgence;
    }
    
    public void setIdAgence(int idAgence) {
        this.idAgence = idAgence;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }




}


