package Model;
// Generated 8 juil. 2018 20:33:07 by Hibernate Tools 4.3.1



/**
 * Agence generated by hbm2java
 */
public class Agence  implements java.io.Serializable {


     private int id;
     private String nom;

    public Agence() {
    }

	
    public Agence(int id) {
        this.id = id;
    }
    public Agence(int id, String nom) {
       this.id = id;
       this.nom = nom;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }




}


