package Model;
// Generated 11 juil. 2018 22:30:34 by Hibernate Tools 4.3.1



/**
 * Agence generated by hbm2java
 */
public class Agence  implements java.io.Serializable {


     private int idAgence;
     private String nom;
     private String adresse;
     private String telephone;

    public Agence() {
    }

	
    public Agence(int idAgence) {
        this.idAgence = idAgence;
    }
    public Agence(int idAgence, String nom, String adresse, String telephone) {
       this.idAgence = idAgence;
       this.nom = nom;
       this.adresse = adresse;
       this.telephone = telephone;
    }
   
    public int getIdAgence() {
        return this.idAgence;
    }
    
    public void setIdAgence(int idAgence) {
        this.idAgence = idAgence;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }




}


