package Model;
// Generated 11 juil. 2018 22:30:34 by Hibernate Tools 4.3.1



/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private int idClient;
     private String nom;
     private String prenom;
     private String adresse;
     private String telephone;
     private String password;

    public Client() {
    }

	
    public Client(int idClient) {
        this.idClient = idClient;
    }
    public Client(int idClient, String nom, String prenom, String adresse, String telephone, String password) {
       this.idClient = idClient;
       this.nom = nom;
       this.prenom = prenom;
       this.adresse = adresse;
       this.telephone = telephone;
       this.password = password;
    }
   
    public int getIdClient() {
        return this.idClient;
    }
    
    public void setIdClient(int idClient) {
        this.idClient = idClient;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


