package Model;
// Generated 9 juil. 2018 20:01:58 by Hibernate Tools 4.3.1



/**
 * Compte generated by hbm2java
 */
public class Compte  implements java.io.Serializable {


     private int idCompte;
     private Integer solde;
     private Integer decouvertautorise;

    public Compte() {
    }

	
    public Compte(int idCompte) {
        this.idCompte = idCompte;
    }
    public Compte(int idCompte, Integer solde, Integer decouvertautorise) {
       this.idCompte = idCompte;
       this.solde = solde;
       this.decouvertautorise = decouvertautorise;
    }
   
    public int getIdCompte() {
        return this.idCompte;
    }
    
    public void setIdCompte(int idCompte) {
        this.idCompte = idCompte;
    }
    public Integer getSolde() {
        return this.solde;
    }
    
    public void setSolde(Integer solde) {
        this.solde = solde;
    }
    public Integer getDecouvertautorise() {
        return this.decouvertautorise;
    }
    
    public void setDecouvertautorise(Integer decouvertautorise) {
        this.decouvertautorise = decouvertautorise;
    }




}


