package Model;
// Generated 10 juil. 2018 23:06:08 by Hibernate Tools 4.3.1



/**
 * Compteclient generated by hbm2java
 */
public class Compteclient  implements java.io.Serializable {


     private long id;
     private Integer clientId;
     private Integer compteId;

    public Compteclient() {
    }

	
    public Compteclient(long id) {
        this.id = id;
    }
    public Compteclient(long id, Integer clientId, Integer compteId) {
       this.id = id;
       this.clientId = clientId;
       this.compteId = compteId;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Integer getClientId() {
        return this.clientId;
    }
    
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }
    public Integer getCompteId() {
        return this.compteId;
    }
    
    public void setCompteId(Integer compteId) {
        this.compteId = compteId;
    }




}


