package Model;
// Generated 8 juil. 2018 20:33:07 by Hibernate Tools 4.3.1



/**
 * Compte generated by hbm2java
 */
public class Compte  implements java.io.Serializable {


     private int id;
     private Integer solde;
     private Integer decouvertautorise;

    public Compte() {
    }

	
    public Compte(int id) {
        this.id = id;
    }
    public Compte(int id, Integer solde, Integer decouvertautorise) {
       this.id = id;
       this.solde = solde;
       this.decouvertautorise = decouvertautorise;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getSolde() {
        return this.solde;
    }
    
    public void setSolde(Integer solde) {
        this.solde = solde;
    }
    public Integer getDecouvertautorise() {
        return this.decouvertautorise;
    }
    
    public void setDecouvertautorise(Integer decouvertautorise) {
        this.decouvertautorise = decouvertautorise;
    }




}


