package Model;
// Generated 11 juil. 2018 21:07:29 by Hibernate Tools 4.3.1



/**
 * Conseiller generated by hbm2java
 */
public class Conseiller  implements java.io.Serializable {


     private int idConseiller;
     private String nom;
     private String prenom;
     private String telephone;
     private String password;
     private Integer agenceId;

    public Conseiller() {
    }

	
    public Conseiller(int idConseiller) {
        this.idConseiller = idConseiller;
    }
    public Conseiller(int idConseiller, String nom, String prenom, String telephone, String password, Integer agenceId) {
       this.idConseiller = idConseiller;
       this.nom = nom;
       this.prenom = prenom;
       this.telephone = telephone;
       this.password = password;
       this.agenceId = agenceId;
    }
   
    public int getIdConseiller() {
        return this.idConseiller;
    }
    
    public void setIdConseiller(int idConseiller) {
        this.idConseiller = idConseiller;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getAgenceId() {
        return this.agenceId;
    }
    
    public void setAgenceId(Integer agenceId) {
        this.agenceId = agenceId;
    }




}


