package Model;
// Generated 10 juil. 2018 23:06:08 by Hibernate Tools 4.3.1



/**
 * Conseiller generated by hbm2java
 */
public class Conseiller  implements java.io.Serializable {


     private int idConseiller;
     private String nom;
     private String prenom;
     private String adresse;
     private String telephone;
     private Integer agence;
     private String password;

    public Conseiller() {
    }

	
    public Conseiller(int idConseiller) {
        this.idConseiller = idConseiller;
    }
    public Conseiller(int idConseiller, String nom, String prenom, String adresse, String telephone, Integer agence, String password) {
       this.idConseiller = idConseiller;
       this.nom = nom;
       this.prenom = prenom;
       this.adresse = adresse;
       this.telephone = telephone;
       this.agence = agence;
       this.password = password;
    }
   
    public int getIdConseiller() {
        return this.idConseiller;
    }
    
    public void setIdConseiller(int idConseiller) {
        this.idConseiller = idConseiller;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public Integer getAgence() {
        return this.agence;
    }
    
    public void setAgence(Integer agence) {
        this.agence = agence;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


