package Model;
// Generated 11 juil. 2018 22:30:34 by Hibernate Tools 4.3.1



/**
 * JourId generated by hbm2java
 */
public class JourId  implements java.io.Serializable {


     private int idJour;
     private int agenceId;

    public JourId() {
    }

    public JourId(int idJour, int agenceId) {
       this.idJour = idJour;
       this.agenceId = agenceId;
    }
   
    public int getIdJour() {
        return this.idJour;
    }
    
    public void setIdJour(int idJour) {
        this.idJour = idJour;
    }
    public int getAgenceId() {
        return this.agenceId;
    }
    
    public void setAgenceId(int agenceId) {
        this.agenceId = agenceId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof JourId) ) return false;
		 JourId castOther = ( JourId ) other; 
         
		 return (this.getIdJour()==castOther.getIdJour())
 && (this.getAgenceId()==castOther.getAgenceId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdJour();
         result = 37 * result + this.getAgenceId();
         return result;
   }   


}


