package Model;
// Generated 8 juil. 2018 20:33:07 by Hibernate Tools 4.3.1



/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private long id;
     private Integer idclient;
     private Integer idconseiller;
     private String contenu;

    public Message() {
    }

	
    public Message(long id) {
        this.id = id;
    }
    public Message(long id, Integer idclient, Integer idconseiller, String contenu) {
       this.id = id;
       this.idclient = idclient;
       this.idconseiller = idconseiller;
       this.contenu = contenu;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Integer getIdclient() {
        return this.idclient;
    }
    
    public void setIdclient(Integer idclient) {
        this.idclient = idclient;
    }
    public Integer getIdconseiller() {
        return this.idconseiller;
    }
    
    public void setIdconseiller(Integer idconseiller) {
        this.idconseiller = idconseiller;
    }
    public String getContenu() {
        return this.contenu;
    }
    
    public void setContenu(String contenu) {
        this.contenu = contenu;
    }




}


