package Model;
// Generated 8 juil. 2018 20:33:07 by Hibernate Tools 4.3.1



/**
 * Transactions generated by hbm2java
 */
public class Transactions  implements java.io.Serializable {


     private int id;
     private Integer idcomptecredit;
     private Integer idcomptedebite;
     private Integer idclient;

    public Transactions() {
    }

	
    public Transactions(int id) {
        this.id = id;
    }
    public Transactions(int id, Integer idcomptecredit, Integer idcomptedebite, Integer idclient) {
       this.id = id;
       this.idcomptecredit = idcomptecredit;
       this.idcomptedebite = idcomptedebite;
       this.idclient = idclient;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getIdcomptecredit() {
        return this.idcomptecredit;
    }
    
    public void setIdcomptecredit(Integer idcomptecredit) {
        this.idcomptecredit = idcomptecredit;
    }
    public Integer getIdcomptedebite() {
        return this.idcomptedebite;
    }
    
    public void setIdcomptedebite(Integer idcomptedebite) {
        this.idcomptedebite = idcomptedebite;
    }
    public Integer getIdclient() {
        return this.idclient;
    }
    
    public void setIdclient(Integer idclient) {
        this.idclient = idclient;
    }




}


